#' wildrtrax: A series of functions for environmental sensor data management and analysis to and from WildTrax
#'
#' @author Alex MacPhail \email{agmacpha@ualberta.ca}
#' @docType package
#' @name wildrtrax
"_PACKAGE"

# Define global variables
utils::globalVariables(
  c(
    ".",
    ":=",
    "AUTO ID*",
    "DATE",
    "DURATION",
    "Dur",
    "FileName",
    "Fmax",
    "Fmin",
    "IN FILE",
    "INDIR",
    "OFFSET",
    "max_seconds",
    "max_time",
    "Quality",
    "RankOrder",
    "ResultMinute",
    "ResultStartSeconds",
    "Score",
    "SegmentDurationSeconds",
    "TIME",
    "ZeroSignal",
    "abundance",
    "aru_task_status",
    "clip_url",
    "confidence",
    "counts",
    "data",
    "detection",
    "detection_time",
    "detections",
    "distance_to",
    "end_date",
    "end_time",
    "end_time_s",
    "file_name",
    "file_path",
    "file_type",
    "flac_info",
    "fullNm",
    "geometry",
    "image_date_time",
    "image_id",
    "index_value",
    "index_variable",
    "individual_count",
    "individual_order",
    "internal_tag_id",
    "is_species_allowed_in_project",
    "latitude",
    "length_seconds",
    "list_all",
    "location.x",
    "location.y",
    "location_from",
    "longer",
    "longitude",
    "MANUAL ID",
    "maxFreq",
    "max_animals",
    "method",
    "minFreq",
    "new_detection",
    "observer_id",
    "occur",
    "org_code",
    "org_id",
    "location_visibility",
    "type",
    "organization",
    "organizationId",
    "organizationName",
    "lowerleft",
    "upperleft",
    "upperright",
    "lowerright",
    "center",
    "lowerleft_lon",
    "lowerleft_lat",
    "upperleft_lon",
    "upperleft_lat",
    "upperright_lon",
    "upperright_lat",
    "lowerright_lon",
    "lowerright_lat",
    "GRTS_ID",
    "GRTS_suffix",
    "packageVersion",
    "pred",
    "presence",
    "project_id",
    "recordingDate",
    "recording_date_time",
    "sensorId",
    "size_Mb",
    "species",
    "speciesIndividualNumber",
    "species_class",
    "species_code",
    "species_common_name",
    "species_individual_comments",
    "spectrogram_url",
    "startTime",
    "start_date",
    "start_time",
    "start_time_s",
    "start_times",
    "status",
    "tagLength",
    "tag_is_verified",
    "taskLength",
    "task_method",
    "tasks",
    "time_lag",
    "tp",
    "transcriber",
    "unsafe",
    "spp_t",
    "spp",
    "full_bounds",
    "all_rpps_tibble",
    "all_result_tables",
    "unzip",
    "visit",
    "vocalization",
    "wac_info",
    "value",
    "species_id",
    "projectId",
    "project_name",
    "species_scientific_name",
    "write.csv",
    "recording_url",
    "audio_file_type",
    "chardis",
    "chardismax",
    "chardur",
    "chardurmax",
    "distance1",
    "survey_id",
    "survey_date",
    "survey_duration_method",
    "observer",
    "durationMethod",
    "survey_distance_method",
    "task_id",
    "task_duration",
    "task_distance",
    "location_id",
    "is_missing",
    "n_days_effort",
    "sensor",
    "col_type_index",
    "cols",
    "time",
    "distance",
    "fp",
    "precision",
    "recall",
    "is_species_allowed_in_project",
    "start_s",
    "confidence",
    "recording_id",
    "human",
    "classifier",
    "fscore",
    "visit_date", "crew", "land_features", "deployment_date", "retrieval_date",
    "equipment_condition", "equipment_direction", "equipment_mount", "stake_distance",
    "location_buffer_m", "sfw_name", "age_class", "sex_class", "sd_effectiveDate",
    "sc_SURVEYTYPE.domainCodeIdSurveyType", "sd_terminationDate",
    "day",
    "image_fov",
    "interval",
    "crossing",
    "isoweek",
    "minute",
    "month",
    "parse_date_time",
    "period",
    "spps",
    "u",
    "week",
    "year",
    "start_date","end_date","typ","length_sec",
    "allImages", "endDate", "firstVisit", "first_visit_date", "hasImage",
    "image_set_end_date", "image_set_start_date", "lastVisit", "last_visit_date",
    "locationId", "locationName", "motionImages", "startDate", "taskCount",
    "birdNetSpeciesIds", "bufferRadius", "buffer_m", "code", "creationDate",
    "deploymentDate", "directionDegree", "dirpath", "dueDate", "filename", "filepath",
    "hawkEarSpeciesIds", "image", "imageCount", "image_crop", "image_info",
    "individual_number", "isTrueCoordinates", "is_complete", "level", "localAreaName",
    "make", "max_tag_freq", "min_tag_freq", "model", "my_output_file", "name", "option",
    "organization_id", "organization_name", "parentEquipment", "parentfolder", "path",
    "project_creation_date", "project_due_date", "project_sensor", "project_status",
    "recognizer", "recordingAudioLength", "recordingCount",
    "recording_sample_frequency", "retrieveDate", "serialNo", "speciesIds",
    "species_code.x", "species_code.y", "species_individual_number", "species_order",
    "stakeDistance", "tag_duration", "tag_is_hidden_for_verification",
    "tag_max_freq", "tag_min_freq", "tag_start_time", "task_count", "task_length",
    "tasksCompleted", "tasks_completed", "unnest_wider", "visibilityId", "visitCount",
    "tagger_list",
    "user_id",
    "pudId",
    "project_Id",
    "statusId",
    "taggerUserId",
    "motionImageCount",
    "totalImageCount",
    "tagCount",
    "imagesTaggedCount",
    "user_name",
    "image_set_status",
    "taskId",
    "methodId",
    "isComplete",
    "transcriberUserId",
    "frequency",
    "uploadDate",
    "individualCount",
    "detectedSpeciesIds",
    "recordingURL"
  )
)
